name: GCS Cache Benchmark (Self-hosted c4d)

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  gcs-cache:
    runs-on: self-hosted
  

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Authenticate with GCP via OIDC
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: gh-runner@clientgcp-462908.iam.gserviceaccount.com
        env:
          GOOGLE_GHA_DEBUG: true
      - name: Debug JWT claims
        run: |
          echo "${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" | base64 --decode | jq
        env:
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ steps.auth.outputs.id_token }}
      - name: Restore or Save cache via GCS
        id: cache
        uses: mansagroup/gcs-cache-action@v1.0.3
        with:
          bucket: ci-cache-node-1720123456
          path: node_modules
          key: node-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: node-

      - name: Install dependencies if cache miss
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Summary
        run: |
          du -sh node_modules || true
          echo "cache_hit=${{ steps.cache.outputs.cache-hit }}" >> $GITHUB_STEP_SUMMARY
