
name: WIF-debug

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  debug:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CLOUD_PROJECT: clientgcp-462908

    steps:
      - run: echo "WIF_PROVIDER=${{ secrets.WIF_PROVIDER }}"
      - name: Set up gcloud with WIF
        id: gcp-auth
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: clientgcp-462908
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account_email: gh-runner@clientgcp-462908.iam.gserviceaccount.com
          export_default_credentials: true
        env:
          GOOGLE_GHA_DEBUG: true
      - name: Dump Auth Info
        run: |
           echo "Credentials file: ${{ steps.gcp-auth.outputs.credentials_file_path }}"
           echo "Service Account: ${{ steps.gcp-auth.outputs.service_account_email }}"
           gcloud auth list
           gcloud config list


      - run: |
          echo "Active account:"
          gcloud auth list --filter="STATUS:ACTIVE"
          echo "ADC file path: ${{ steps.gcp-auth.outputs.credentials_file_path }}"