{
    "name": "root",
    "private": true,
    "license": "GPL-3.0",
    "scripts": {
      "build": "node index.js"
    },
    "resolutions": {
        "@pdf-lib/standard-fonts@^1.0.0": "patch:@pdf-lib/standard-fonts@npm%3A1.0.0#./.yarn/patches/@pdf-lib-standard-fonts-npm-1.0.0-963255903e.patch",
        "@storybook/react-docgen-typescript-plugin": "1.0.6--canary.9.f9c48c0.0",
        "electron-winstaller": "^5.4.0",
        "json5": "^2.2.3",
        "merge": "^2.1.1",
        "node-gyp": "^11.2.0",
        "rfc2047@^2.0.1": "patch:rfc2047@npm%3A2.0.1#./.yarn/patches/rfc2047-npm-2.0.1-60a2a07c99.patch",
        "safe-buffer": "^5.2.1",
        "terser": "^5.43.1",
        "whatwg-url": "^14.2.0"
    },
    "dependencies": {
        "@payloadcms/db-postgres": "3.33.0",
        "@payloadcms/live-preview-react": "^3.33.0",
        "@payloadcms/next": "3.33.0",
        "@payloadcms/payload-cloud": "3.33.0",
        "@payloadcms/plugin-form-builder": "3.33.0",
        "@payloadcms/plugin-nested-docs": "3.33.0",
        "@payloadcms/plugin-seo": "3.33.0",
        "@payloadcms/richtext-lexical": "3.33.0",
        "@payloadcms/storage-s3": "3.33.0",
        "@payloadcms/ui": "3.33.0",
        "common": "workspace:*",
        "config": "workspace:*",
        "cross-env": "^7.0.3",
        "eslint-config-supabase": "workspace:*",
        "graphql": "^16.8.1",
        "next": "catalog:",
        "payload": "3.33.0",
        "react": "catalog:",
        "react-dom": "catalog:",
        "sharp": "0.32.6",
        "@hookform/resolvers": "^3.1.1",
        "contentlayer2": "0.4.6",
        "icons": "workspace:*",
        "jotai": "^2.8.0",
        "lucide-react": "*",
        "markdown-wasm": "^1.2.0",
        "next-contentlayer2": "0.4.6",
        "next-themes": "^0.3.0",
        "react-docgen": "^7.0.3",
        "react-hook-form": "^7.45.0",
        "react-inlinesvg": "^4.0.4",
        "react-wrap-balancer": "^1.1.0",
        "recharts": "^2.12.7",
        "rehype-autolink-headings": "^7.1.0",
        "rehype-pretty-code": "^0.9.0",
        "rehype-slug": "^6.0.0",
        "remark": "^14.0.3",
        "remark-code-import": "^1.2.0",
        "remark-gfm": "^4.0.0",
        "sonner": "^1.5.0",
        "ts-morph": "^22.0.0",
        "ui": "workspace:*",
        "ui-patterns": "workspace:*",
        "unist-util-visit": "^5.0.0",
        "zod": "^3.22.4"
    },
    "devDependencies": {
        "@trivago/prettier-plugin-sort-imports": "^5.2.2",
        "@types/jest-when": "^3.5.5",
        "danger": "^12.3.4",
        "husky": "^9.1.7",
        "lint-staged": "^16.1.2",
        "nyc": "^17.1.0",
        "prettier": "^3.6.2",
        "sort-package-json": "^3.3.1",
        "turbo": "^2.5.4"
    },
    "packageManager": "yarn@4.9.2",
    "engines": {
        "node": ">= 22.14.0 "
    },
    "publishConfig": {
        "registry": "https://nexus.protontech.ch/repository/web-npm/"
    }
}
