name: GitHub Cache Benchmark (Azure Blob)

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  github-cache:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate package-lock.json
        run: npm install --package-lock-only

      - name: Restore cache from GitHub (Azure)
        id: restore
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: node-

      - name: Install dependencies if cache miss
        if: steps.restore.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Save cache to GitHub (Azure)
        if: steps.restore.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Summary
        run: |
          du -sh node_modules || true
          echo "cache_hit=${{ steps.restore.outputs.cache-hit }}" >> $GITHUB_STEP_SUMMARY
