name: Github Benchmark

on:
  push:
    branches:
      - '*'
  workflow_dispatch:   # you can also add schedule: if you like

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x scripts/cache-bench.sh

      - name: Generate 9 GiB test data
        run: |
          mkdir -p cache-data
          dd if=/dev/zero of=cache-data/test-9gb.bin bs=1M count=9216 status=progress

      - name: Save cache (upload)
        uses: actions/cache@v3
        with:
          path: cache-data
          key: cache-benchmark-9gb

      - name: Clear local data
        run: rm -rf cache-data

      - name: Restore cache (download)
        uses: actions/cache@v3
        with:
          path: cache-data
          key: cache-benchmark-9gb
